HotelsApplication_new/HotelsApplication/Models/HotelsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HotelsApplication.Models
{
    public class HotelsViewModel
    {
        public List<Hotels> HotelsList { get; set; }
        public List<Cities> CitiesList { get; set; }
        public Hotels SelectedHotel { get; set; }
        public string DisplayMode { get; set; }
    }
}

HotelsApplication_new/HotelsApplication/Controllers/HotelsController.cs
using HotelsApplication.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HotelsApplication.Controllers
{
    public class HotelsController : Controller
    {
        private HotelsAppEntities db = new HotelsAppEntities();
        private HotelsViewModel hotelsModel = new HotelsViewModel();


        public ActionResult Index()
        {
            hotelsModel.HotelsList = db.Hotels.ToList();
            hotelsModel.SelectedHotel = null;
            return View(hotelsModel);
        }


        public ActionResult Details(int id = 0)
        {
            hotelsModel.HotelsList = db.Hotels.ToList();
            hotelsModel.SelectedHotel = db.Hotels.Find(id);
            hotelsModel.DisplayMode = "displayHotel";            
            if (hotelsModel.SelectedHotel == null)
            {
                return HttpNotFound();
            }
            return PartialView("ShowHotel", hotelsModel.SelectedHotel);
        }
        
        public ActionResult Create()
        {
            hotelsModel.HotelsList = db.Hotels.ToList();
            hotelsModel.SelectedHotel = null;
            hotelsModel.DisplayMode = "addHotel";
            return PartialView("insertHotel", hotelsModel.SelectedHotel);
        }

        [HttpPost]
        public ActionResult Insert(Hotels hotels)
        {
            if (ModelState.IsValid)
            {
                db.Hotels.Add(hotels);
                db.SaveChanges();

                hotelsModel.HotelsList = db.Hotels.ToList();
                hotelsModel.SelectedHotel = db.Hotels.Find(hotels.HotelID);
//                hotelsModel.DisplayMode = "displayHotel";             
            }
            return View("Index", hotelsModel);
        }


        [HttpPost]    
        public ActionResult Edit(int id = 0)
        {
            hotelsModel.HotelsList = db.Hotels.ToList();
            hotelsModel.SelectedHotel = db.Hotels.Find(id);
            hotelsModel.DisplayMode = "updateHotel";
            if (hotelsModel.SelectedHotel == null)
            {
                return HttpNotFound();
            }
            return View("Index", hotelsModel);
        }

        [HttpPost]
        public ActionResult Update(Hotels hotels)
        {
            if (ModelState.IsValid)
            {
                Hotels currentHotel = db.Hotels.Find(hotels.HotelID);
                currentHotel.hotel_name = hotels.hotel_name;
                currentHotel.hotel_latitude = hotels.hotel_latitude;
                currentHotel.hotel_longitude = hotels.hotel_longitude;
                currentHotel.address = hotels.address;
                currentHotel.phone = hotels.phone;
                currentHotel.category = hotels.category;
                currentHotel.lowest_rate = hotels.lowest_rate;
                currentHotel.hotel_description = hotels.hotel_description;
                db.SaveChanges();

                hotelsModel.HotelsList = db.Hotels.ToList();
                hotelsModel.SelectedHotel = currentHotel;
                //hotelsModel.DisplayMode = "displayHotel";
            }
            return View("Index", hotelsModel);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            if (!id.Equals(null))
            {
                Hotels currentHotel = db.Hotels.Find(id);
                db.Hotels.Remove(currentHotel);
                db.SaveChanges();

                hotelsModel.HotelsList = db.Hotels.ToList();
                hotelsModel.SelectedHotel = null;
                hotelsModel.DisplayMode = "";
            }
            return JavaScript("location.reload(true)");
        }

        [HttpPost]
        public ActionResult Cancel(int id)
        {
            hotelsModel.HotelsList = db.Hotels.ToList();
            hotelsModel.SelectedHotel = db.Hotels.Find(id);
            hotelsModel.DisplayMode = "displayHotel";
            return View("Index", hotelsModel);

        }

        public ActionResult APIClient()
        {
            return View("APIClient");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

HotelsApplication_new/HotelsApplication/Views/Hotels/APIClient.cshtml
@{
    ViewBag.Title = "APIClient";
}

@if (Session["LogedUserFullname"] != null)
{
<!DOCTYPE html>
<header class="header-content">
    <img src="~/Content/themes/base/images/logo-marriott.png" />
    <a href="~/Users/Login" class="button-link logout-button" style="float:right;">Sign Out</a>
    <h4>Hotels Locator Manager | Web API</h4>
    <small>Welcome @Session["LogedUserFullname"].ToString()</small>
</header>   
<html>
<head>
    <meta charset="utf-8" />
    <title>Hotels Locator</title>    
    <link href="@Url.Content("~/Content/HotelsHome.css")" rel="stylesheet" type="text/css" />
    <script src="//code.jquery.com/jquery.min.js" type="text/javascript"></script>
    <script>
        $(function () {
            $('#btn-all').on('click', function () {
                $.get('/api/HotelsAPI', function (data) {
                    $('#result').empty();
                    $.each(data, function (i, v) {
                        $('#result').html($('#result').html() + JSON.stringify(v, null, "<br />\t") + '<br />');
                    });
                }, 'json');
            });
            $('#btn').on('click', function () {
                $.get('/api/HotelsAPI/' + $('#HotelId').val(), function (data) {
                    $('#result').empty()
                    $('#result').html(JSON.stringify(data.hotel_name, null, "\t") +
                        '<br />' + JSON.stringify(data.address, null, "\t") +
                        '<br />' + JSON.stringify(data.hotel_description, null, "\t"));
                }, 'json');
            });
            $('#btn-delete').on('click', function () {
                $.ajax({
                    type: 'Delete',
                    url: '/api/HotelsAPI?id=' + $('#HotelId').val()
                });
            });
        });
    </script>
</head>
<body>    
    <button id="btn-all">Get all Hotels</button> <button id="btn">Get Hotel</button> 
    @Html.TextBox("HotelId")
    <div id="result"></div>
</body>
</html>
}

HotelsApplication_new/HotelsApplication/Views/Hotels/EditHotel.cshtml
@model HotelsApplication.Hotels

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

@using (Html.BeginForm("Update", "Hotels", FormMethod.Post))
{
    <table border="1" cellpadding="10">
        <tr>
            <td>Hotel ID</td>
            <td>@Html.TextBoxFor(model => model.HotelID, new { @readonly = "readonly" })</td>
        </tr>
        <tr>
            <td>Hotel Name</td>
            <td>@Html.EditorFor(model => model.hotel_name)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_name)</td>
        </tr>
        <tr>
            <td>Latitude</td>
            <td>@Html.EditorFor(model => model.hotel_latitude)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_latitude)</td>
        </tr>
        <tr>
            <td>Longitude</td>
            <td>@Html.EditorFor(model => model.hotel_longitude)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_longitude)</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>@Html.EditorFor(model => model.address)</td>
            <td>@Html.ValidationMessageFor(model => model.address)</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td>@Html.EditorFor(model => model.phone)</td>
            <td>@Html.ValidationMessageFor(model => model.phone)</td>
        </tr>
        <tr>
            <td>Category</td>
            <td>@Html.EditorFor(model => model.category)</td>
            <td>@Html.ValidationMessageFor(model => model.category)</td>
        </tr>
        <tr>
            <td>Lowest Rate</td>
            <td>@Html.EditorFor(model => model.lowest_rate)</td>
            <td>@Html.ValidationMessageFor(model => model.lowest_rate)</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>@Html.EditorFor(model => model.hotel_description)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_description)</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Save"
                       formaction="/Hotels/Update" onclick="return confirm('Are you sure you want to Update this Hotel?');" />
                <input type="submit" value="Cancel"
                       formaction="/Hotels/Cancel/@Model.HotelID" />
            </td>
        </tr>
    </table>
}

HotelsApplication_new/HotelsApplication/Views/Hotels/Index.cshtml
@model HotelsApplication.Models.HotelsViewModel
@{
    ViewBag.Title = "Hotels Locator Manager";
}
@if (Session["LogedUserFullname"] != null)
{
    <!DOCTYPE html>
    <header class="header-content">          
            <img src="~/Content/themes/base/images/logo-marriott.png" />                               
            <a href="~/Users/Login" class="button-link logout-button" style="float:right;">Sign Out</a>
            <h4>Hotels Locator Manager | Map</h4>
            <small>Welcome @Session["LogedUserFullname"].ToString()</small>        
    </header>    
    <html>
    <head>
        <link href="@Url.Content("~/Content/HotelsLocator.css")" rel="stylesheet" type="text/css" />
        <meta name="viewport" content="width=device-width" />
        <title>Hotels Locator</title>
        @section scripts{
            @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
        }
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBk7K1ZaMBPBlhN39szHlQ8PWw0dsj15IA">
        </script>
        <script type="text/javascript">
            var map;
            var mapOptions;
            var markers = new Map();

            function initialize() {
                mapOptions = {
                    center: { lat: 21.8890872, lng: -102.2919885 },
                    zoom: 4
                };
                map = new google.maps.Map(document.getElementById('map-canvas'),
                    mapOptions);
                @foreach (var item in Model.HotelsList)
            {
                @:addMarker(@item.hotel_latitude, @item.hotel_longitude, '@item.hotel_name', '@item.hotel_description', map);
                            }
            }

            function addMarker(latitude, longitude, title, description, map) {
                var latLng = new google.maps.LatLng(latitude, longitude);
                var contentString = '<h3>' + title + '</h3>' + '<p>' + description + '</p>';

                var infowindow = new google.maps.InfoWindow({
                    content: contentString
                });

                var marker = new google.maps.Marker({
                    position: latLng,
                    title: title,
                    map: map,
                    draggable: false
                });

                google.maps.event.addListener(marker, 'click', function () {
                    infowindow.open(map, marker);
                });

                markers.set(marker.title, marker.position);
            }
            google.maps.event.addDomListener(window, 'load', initialize);

            function searchHotel() {
                for (var mrk of markers.keys()) {
                    if(mrk.toLowerCase().indexOf(document.getElementById("hotelParam").value.toLowerCase()) > -1){
                        map.setCenter(markers.get(mrk));
                        map.setZoom(15);
                    }
                }
            }

            function getSelectedHotel(latitude, longitude) {
                var latLng = new google.maps.LatLng(latitude, longitude);
                map.setCenter(latLng);
                map.setZoom(15);
            }
        </script>        
    </head>            
    <body>        
        <div id="mainContent">
            @Ajax.ActionLink("Insert", "Create", new { }, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "selectedHotel" }, new { @class = "button-link" })
            <br /><br />
            <input type="text" id="hotelParam" oninput="searchHotel()" />
            <br /><br />
            <div id="map-canvas" style="width: 550px; height: 350px; float: left; margin: 0; padding: 0;"> </div>
            <div style="width: auto; float: left; margin: 0; padding: 0;">
                <table border="1" cellpadding="10">
                    @foreach (var item in Model.HotelsList)
                    {
                        if (Model.SelectedHotel != null)
                        {
                            if (item.HotelID == Model.SelectedHotel.HotelID)
                            {
                                @:<tr class="SelectedHotel">
                    }
                            else
                            {
                                @:<tr>
                    }
                        }
                        else
                        {
                            @:<tr>
                }
                <td onclick="getSelectedHotel(@item.hotel_latitude, @item.hotel_longitude)">@Ajax.ActionLink(@item.hotel_name, "Details", new { id = @item.HotelID }, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "selectedHotel" })</td>
                        <td>@Ajax.ActionLink("Delete", "Delete", new { id = @item.HotelID }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to delete this hotel?" })</td>
                        @:</tr>
            }
                </table>
            </div>
            <div id="selectedHotel" style="float: left; margin: 0; padding: 0;">
                @{
                    if (Model.SelectedHotel != null)
                    {
                        if (Model.DisplayMode == "displayHotel")
                        {
                            Html.RenderPartial("ShowHotel", Model.SelectedHotel);
                        }
                        if (Model.DisplayMode == "updateHotel")
                        {
                            Html.RenderPartial("EditHotel", Model.SelectedHotel);
                        }
                    }
                    if (Model.DisplayMode == "addHotel")
                    {
                        Html.RenderPartial("InsertHotel", new HotelsApplication.Hotels());
                    }
                }
            </div>
        </div>
        <div class="accordion vertical">
            <section id="home">
                <h2><a href="~/Users/HotelsLocator">Home</a></h2>                
            </section>
            <section id="appModules">
                <h2><a href="#appModules">Application Modules</a></h2>
                <p><a href="~/Hotels/Index" class="menu-link">Hotels Map</a></p>
                <p><a href="~/Hotels/APIClient" class="menu-link">Hotels Web API</a></p>
            </section>
            <section id="appLogs">
                <h2><a href="#appLogs">Application Logs</a></h2>
                <p><a href="~/Users/AdminUsers" class="menu-link">Registered Users</a></p>
            </section>
        </div>
    </body>
</html>
}


HotelsApplication_new/HotelsApplication/Views/Hotels/InsertHotel.cshtml
@model HotelsApplication.Hotels

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"></script>

@using (Html.BeginForm("Create", "Hotels", FormMethod.Post))
{
    <table border="1" cellpadding="10">
        <tr>
            <td>Hotel Name</td>
            <td>@Html.EditorFor(model => model.hotel_name)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_name)</td>
        </tr>
        <tr>
            <td>Latitude</td>
            <td>@Html.EditorFor(model => model.hotel_latitude)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_latitude)</td>
        </tr>
        <tr>
            <td>Longitude</td>
            <td>@Html.EditorFor(model => model.hotel_longitude)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_longitude)</td>
        </tr>
        <tr>
            <td>Address</td>
            <td>@Html.EditorFor(model => model.address)</td>
            <td>@Html.ValidationMessageFor(model => model.address)</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td>@Html.EditorFor(model => model.phone)</td>
            <td>@Html.ValidationMessageFor(model => model.phone)</td>
        </tr>
        <tr>
            <td>Category</td>
            <td>@Html.EditorFor(model => model.category)</td>
            <td>@Html.ValidationMessageFor(model => model.category)</td>
        </tr>
        <tr>
            <td>Lowest Rate</td>
            <td>@Html.EditorFor(model => model.lowest_rate)</td>
            <td>@Html.ValidationMessageFor(model => model.lowest_rate)</td>
        </tr>
        <tr>
            <td>Description</td>
            <td>@Html.EditorFor(model => model.hotel_description)</td>
            <td>@Html.ValidationMessageFor(model => model.hotel_description)</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Save"
                       formaction="/Hotels/Insert" />
                <input type="submit" value="Cancel"
                       formaction="/Hotels/Index" />
            </td>
        </tr>
    </table>
}

HotelsApplication_new/HotelsApplication/Views/Hotels/ShowHotel.cshtml
@model HotelsApplication.Hotels

@using (Html.BeginForm("Edit", "Hotels", FormMethod.Post))
{
    <table border="1" cellpadding="10">
        <tr>
            <td>Hotel Name :</td>
            <td>@Model.hotel_name</td>
        </tr>
        <tr>
            <td>Latitude :</td>
            <td>@Model.hotel_latitude</td>
        </tr>
        <tr>
            <td>Longitude :</td>
            <td>@Model.hotel_longitude</td>
        </tr>
        <tr>
            <td>Address :</td>
            <td>@Model.address</td>
        </tr>
        <tr>
            <td>Phone :</td>
            <td>@Model.phone</td>
        </tr>
        <tr>
            <td>Category :</td>
            <td>@Model.category</td>
        </tr>
        <tr>
            <td>Lowest Rate :</td>
            <td>@Model.lowest_rate</td>
        </tr>
        <tr>
            <td>Description :</td>
            <td>@Model.hotel_description</td>
        </tr>
        <tr>
            <td colspan="2">
                <input type="submit" value="Update"
                       formaction="/Hotels/Edit/@Model.HotelID" />
                <input type="submit" value="Cancel"
                       formaction="/Hotels/Index" />
            </td>
        </tr>
    </table>
}